create table if not exists public.project_submittal_packets (
  id bigint generated by default as identity primary key,
  job_id bigint not null unique references public.jobs(id) on delete cascade,
  packet_title text not null default 'Product Submittal Package',
  prepared_for text,
  prepared_by text,
  revision text,
  issue_date date,
  cover_notes text,
  created_by_user_id bigint references public.users(id) on delete set null,
  updated_by_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_submittal_items (
  id bigint generated by default as identity primary key,
  packet_id bigint not null references public.project_submittal_packets(id) on delete cascade,
  section_number text,
  title text not null,
  manufacturer text,
  product_name text,
  model_number text,
  notes text,
  sort_order integer not null default 0,
  created_by_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_submittal_files (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.project_submittal_items(id) on delete cascade,
  file_name text not null,
  storage_bucket text not null default 'entity-files',
  storage_key text not null unique,
  mime_type text not null default 'application/pdf',
  size_bytes bigint not null default 0 check (size_bytes >= 0),
  page_count integer not null default 0 check (page_count >= 0),
  created_by_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_project_submittal_items_packet_sort
  on public.project_submittal_items(packet_id, sort_order, id);

create index if not exists idx_project_submittal_files_item
  on public.project_submittal_files(item_id, id);

drop trigger if exists trg_project_submittal_packets_updated_at on public.project_submittal_packets;
create trigger trg_project_submittal_packets_updated_at
  before update on public.project_submittal_packets
  for each row execute function public.set_updated_at_column();

drop trigger if exists trg_project_submittal_items_updated_at on public.project_submittal_items;
create trigger trg_project_submittal_items_updated_at
  before update on public.project_submittal_items
  for each row execute function public.set_updated_at_column();

alter table public.project_submittal_packets enable row level security;
alter table public.project_submittal_items enable row level security;
alter table public.project_submittal_files enable row level security;

create policy "project_submittal_packets service role all"
  on public.project_submittal_packets for all to service_role using (true) with check (true);

create policy "project_submittal_items service role all"
  on public.project_submittal_items for all to service_role using (true) with check (true);

create policy "project_submittal_files service role all"
  on public.project_submittal_files for all to service_role using (true) with check (true);

comment on table public.project_submittal_packets is
  'Editable project-level cover information for a generated product submittal packet.';

comment on table public.project_submittal_items is
  'Ordered product-spec sections included in a project submittal packet.';

comment on table public.project_submittal_files is
  'Private PDF product-spec attachments merged into a generated project submittal packet.';
