begin;

alter table public.accounts
  add column if not exists qbo_account_type text,
  add column if not exists detail_type text,
  add column if not exists sort_order integer;

with recon_accounts(code, name, type, qbo_account_type, detail_type, sort_order) as (
  values
    ('11021', 'Checking Account', 'asset', 'Bank', 'Checking', 1),
    ('6305', 'Cash on hand', 'asset', 'Bank', 'Cash on hand', 2),
    ('QB-11025 Business Savings', '11025 Business Savings', 'asset', 'Bank', 'Savings', 3),
    ('QB-2113', '2113', 'asset', 'Bank', 'Cash on hand', 4),
    ('11051', 'Receivables-Trade', 'asset', 'Accounts receivable (A/R)', 'Accounts Receivable (A/R)', 5),
    ('11052', 'Less Allow. for Doubtful', 'asset', 'Other Current Assets', 'Other Current Assets', 6),
    ('11053', 'Receivables-Officer', 'asset', 'Other Current Assets', 'Other Current Assets', 7),
    ('11056', 'Other Current Assets', 'asset', 'Other Current Assets', 'Other Current Assets', 8),
    ('1106', 'Cost in Progress', 'asset', 'Other Current Assets', 'Other Current Assets', 9),
    ('11072', 'Prepaid Insurance', 'asset', 'Other Current Assets', 'Other Current Assets', 10),
    ('11073', 'Prepaid Tax', 'asset', 'Other Current Assets', 'Other Current Assets', 11),
    ('11074', 'Prepaid Interest', 'asset', 'Other Current Assets', 'Other Current Assets', 12),
    ('11100', 'Prepaid Job Materials', 'asset', 'Other Current Assets', 'Prepaid Expenses', 13),
    ('11500', 'Prepaid Payroll', 'asset', 'Other Current Assets', 'Employee Cash Advances', 14),
    ('12000', 'Undeposited Funds', 'asset', 'Other Current Assets', 'Undeposited Funds', 15),
    ('12011', 'Original Value-Vehicles', 'asset', 'Other Current Assets', 'Other Current Assets', 16),
    ('12012', 'Accum. Deprec.-Vehicles', 'asset', 'Other Current Assets', 'Other Current Assets', 17),
    ('12021', 'Orig.Value-Warehouse Eqpt', 'asset', 'Other Current Assets', 'Other Current Assets', 18),
    ('12022', 'Accum.Dep.Warehouse Eqpt.', 'asset', 'Other Current Assets', 'Other Current Assets', 19),
    ('12031', 'Orig. Value-Office Equip.', 'asset', 'Other Current Assets', 'Other Current Assets', 20),
    ('12032', 'Accum. Dep.-Office Equip.', 'asset', 'Other Current Assets', 'Other Current Assets', 21),
    ('1210', 'Employee Advance', 'asset', 'Other Current Assets', 'Other Current Assets', 22),
    ('1401', 'Rent/Lease Deposits', 'asset', 'Other Current Assets', 'Other Current Assets', 23),
    ('QB-Exchange', 'Exchange', 'asset', 'Other Current Assets', 'Other Current Assets', 24),
    ('QB-Inventory Asset', 'Inventory Asset', 'asset', 'Other Current Assets', 'Inventory', 25),
    ('QB-Payroll Refunds', 'Payroll Refunds', 'asset', 'Other Current Assets', 'Other Current Assets', 26),
    ('QB-QuickBooks Payroll Tax Impound', 'QuickBooks Payroll Tax Impound', 'asset', 'Other Current Assets', 'Other Current Assets', 27),
    ('QB-QuickBooks Tax Holding Account', 'QuickBooks Tax Holding Account', 'asset', 'Other Current Assets', 'Other Current Assets', 28),
    ('QB-Uncategorized Asset', 'Uncategorized Asset', 'asset', 'Other Current Assets', 'Other Current Assets', 29),
    ('2102', 'Accounts Payable - Trade', 'liability', 'Accounts payable (A/P)', 'Accounts Payable (A/P)', 30),
    ('QB-Chase Bank', 'Chase Bank', 'liability', 'Credit Card', 'Credit Card', 31),
    ('2100', 'Accrued Expenses', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 32),
    ('21008', 'Note Payable- Sharon Reoch', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 33),
    ('21009', 'Note Payable - Gerald Reoch', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 34),
    ('2101', 'Current Maturities- LTD', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 35),
    ('2103', 'Billings in Progress', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 36),
    ('21052', 'FICA W/H EMPLOYEE', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 37),
    ('21053', 'FICA W/H Employer', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 38),
    ('21054', 'FUTA29', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 39),
    ('21055', 'SUTA30', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 40),
    ('21057', 'Miscellaneous W/H', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 41),
    ('2111', 'Note Payable-Officer', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 42),
    ('2113', 'Credit Line- Chase Bank', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 43),
    ('2160', 'Accrued Distributions - Eric', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 44),
    ('2165', 'Accrued Distributions - Christopher', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 45),
    ('2170', 'Accrued Distributions - Michael', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 46),
    ('22', 'Long Term Debt(Net of CM)', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 47),
    ('22000', 'Deferred Revenue', 'liability', 'Other Current Liabilities', 'Deferred Revenue', 48),
    ('22010', 'MI FET Payable', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 49),
    ('QB-Payroll Liabilities', 'Payroll Liabilities', 'liability', 'Other Current Liabilities', 'Payroll Tax Payable', 50),
    ('21051', 'Payroll Liabilities:Federal Income W/H', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 51),
    ('21056', 'Payroll Liabilities:State Income W/H', 'liability', 'Other Current Liabilities', 'Other Current Liabilities', 52),
    ('QB-Payroll Liabilities:Child/Support', 'Payroll Liabilities:Child/Support', 'liability', 'Other Current Liabilities', 'Payroll Tax Payable', 53),
    ('QB-Payroll Liabilities:Dependant Health Insurance', 'Payroll Liabilities:Dependant Health Insurance', 'liability', 'Other Current Liabilities', 'Payroll Tax Payable', 54),
    ('QB-Payroll Liabilities:Federal Taxes (941/944)', 'Payroll Liabilities:Federal Taxes (941/944)', 'liability', 'Other Current Liabilities', 'Payroll Tax Payable', 55),
    ('QB-Payroll Liabilities:Federal Unemployment (940)', 'Payroll Liabilities:Federal Unemployment (940)', 'liability', 'Other Current Liabilities', 'Payroll Tax Payable', 56),
    ('QB-Payroll Liabilities:MI Income Tax', 'Payroll Liabilities:MI Income Tax', 'liability', 'Other Current Liabilities', 'Payroll Tax Payable', 57),
    ('QB-Payroll Liabilities:MI Unemployment Tax', 'Payroll Liabilities:MI Unemployment Tax', 'liability', 'Other Current Liabilities', 'Payroll Tax Payable', 58),
    ('QB-Payroll Liabilities:PA Income Tax', 'Payroll Liabilities:PA Income Tax', 'liability', 'Other Current Liabilities', 'Payroll Tax Payable', 59),
    ('QB-Payroll Liabilities:PA Local Tax', 'Payroll Liabilities:PA Local Tax', 'liability', 'Other Current Liabilities', 'Payroll Tax Payable', 60),
    ('QB-Repayment', 'Repayment', 'liability', 'Other Current Liabilities', 'Payroll Tax Payable', 61),
    ('QB-Repayment:Repayment on Loan from Recon Enterprises, Inc.', 'Repayment:Repayment on Loan from Recon Enterprises, Inc.', 'liability', 'Other Current Liabilities', 'Payroll Tax Payable', 62),
    ('QB-Sales Tax Agency Payable', 'Sales Tax Agency Payable', 'liability', 'Other Current Liabilities', 'Global Tax Payable', 63),
    ('QB-Sales Tax Vendor Payable', 'Sales Tax Vendor Payable', 'liability', 'Other Current Liabilities', 'Global Tax Payable', 64),
    ('21070', 'Note Payable - New Truck (2020)', 'liability', 'Long Term Liabilities', 'Notes Payable', 65),
    ('2400', 'NP - 2024 Vehicle', 'liability', 'Long Term Liabilities', 'Notes Payable', 66),
    ('31', 'Common Stock', 'equity', 'Equity', 'Owner''s Equity', 67),
    ('34', 'Distributions', 'equity', 'Equity', 'Owner''s Equity', 68),
    ('3400', 'Distributions:Distributions - Sharon', 'equity', 'Equity', 'Partner Distributions', 69),
    ('3410', 'Distributions:Distributions - Eric', 'equity', 'Equity', 'Partner Distributions', 70),
    ('3415', 'Distributions:Distributions - Christopher', 'equity', 'Equity', 'Partner Distributions', 71),
    ('3420', 'Distributions:Distributions - Michael', 'equity', 'Equity', 'Partner Distributions', 72),
    ('35', 'current earnings', 'equity', 'Equity', 'Owner''s Equity', 73),
    ('QB-32 Owners Est. Taxes', '32 Owners Est. Taxes', 'equity', 'Equity', 'Estimated Taxes', 74),
    ('QB-Opening Bal Equity', 'Opening Bal Equity', 'equity', 'Equity', 'Opening Balance Equity', 75),
    ('QB-Retained Earnings', 'Retained Earnings', 'equity', 'Equity', 'Retained Earnings', 76),
    ('4101', 'Sales Construction', 'revenue', 'Income', 'Service/Fee Income', 77),
    ('4102', 'Sales Painting', 'revenue', 'Income', 'Service/Fee Income', 78),
    ('4103', 'Sales Carpeting', 'revenue', 'Income', 'Service/Fee Income', 79),
    ('4104', 'Sales Subcontracting', 'revenue', 'Income', 'Service/Fee Income', 80),
    ('4105', 'SALES RENT', 'revenue', 'Income', 'Service/Fee Income', 81),
    ('4201', 'Returns Construction56', 'revenue', 'Income', 'Service/Fee Income', 82),
    ('4202', 'Returns Painting', 'revenue', 'Income', 'Service/Fee Income', 83),
    ('4203', 'Returns Carpeting', 'revenue', 'Income', 'Service/Fee Income', 84),
    ('4204', 'Returns Construction59', 'revenue', 'Income', 'Service/Fee Income', 85),
    ('QB-*Uncategorized Income', '*Uncategorized Income', 'revenue', 'Income', 'Service/Fee Income', 86),
    ('QB-Billable Expense Income', 'Billable Expense Income', 'revenue', 'Income', 'Service/Fee Income', 87),
    ('QB-Maintenance Income', 'Maintenance Income', 'revenue', 'Income', 'Service/Fee Income', 88),
    ('QB-Markup', 'Markup', 'revenue', 'Income', 'Service/Fee Income', 89),
    ('QB-Sales of Product Income', 'Sales of Product Income', 'revenue', 'Income', 'Sales of Product Income', 90),
    ('QB-Unapplied Cash Payment Income', 'Unapplied Cash Payment Income', 'revenue', 'Income', 'Unapplied Cash Payment Income', 91),
    ('QB-Uncategorized Income', 'Uncategorized Income', 'revenue', 'Income', 'Service/Fee Income', 92),
    ('5101', 'C.O.G.S. Construction', 'expense', 'Cost of Goods Sold', 'Supplies & Materials - COGS', 93),
    ('6603', 'C.O.G.S. Construction:Employee Travel Expenses', 'expense', 'Cost of Goods Sold', 'Cost of labor - COS', 94),
    ('6501', 'Warehouse Rent', 'expense', 'Cost of Goods Sold', 'Other Costs of Services - COS', 95),
    ('6503', 'Lease Equipment', 'expense', 'Cost of Goods Sold', 'Equipment Rental - COS', 96),
    ('6907', 'Permits/Spec''s/Plans', 'expense', 'Cost of Goods Sold', 'Other Costs of Services - COS', 97),
    ('QB-*Cost of Goods Sold', '*Cost of Goods Sold', 'expense', 'Cost of Goods Sold', 'Supplies & Materials - COGS', 98),
    ('QB-Cost of Goods Sold', 'Cost of Goods Sold', 'expense', 'Cost of Goods Sold', 'Supplies & Materials - COGS', 99),
    ('6101', 'Field Wages', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 100),
    ('6102', 'Office Wages', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 101),
    ('6105', 'Warehouse Expense', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 102),
    ('6113', 'FICA Employer', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 103),
    ('6114', 'FUTA70', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 104),
    ('6115', 'SUTA71', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 105),
    ('6116', '940 Tax', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 106),
    ('6406', 'C.E.O. Health Account', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 107),
    ('6407', 'C.E.O. Health Account:Pres. Health Ins.', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 108),
    ('6502', 'Lease Vehicle', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 109),
    ('6504', 'Vehicle Cost', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 110),
    ('6601', 'Milage/Gas/Plate Renewal', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 111),
    ('6602', 'Entertainment/Promotions', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 112),
    ('6701', 'Michigan SBT/Other Taxes', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 113),
    ('6703', 'Bank Service Fees', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 114),
    ('6801', 'Accountant / Lawyer Fees', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 115),
    ('6802', 'Legal Fees', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 116),
    ('6803', 'Computer Consulting', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 117),
    ('6804', 'Advertising', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 118),
    ('6805', 'CORPROATE FILING', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 119),
    ('6900', 'Depreciation Expense', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 120),
    ('6901', 'Telephone/Communications', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 121),
    ('6902', 'Office Supplies/Expense', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 122),
    ('6903', 'Utilities', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 123),
    ('6904', 'Equipment Maintenance', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 124),
    ('6905', 'Vehicle Maint/Tags', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 125),
    ('6908', 'Loan to owners', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 126),
    ('6909', 'Bank Interest', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 127),
    ('6910', 'Postage & Delivery', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 128),
    ('6911', 'Charitable Contributions', 'expense', 'Expenses', 'Charitable Contributions', 129),
    ('69500', 'MI FET Expense', 'expense', 'Expenses', 'Taxes Paid', 130),
    ('QB-*Uncategorized Expenses', '*Uncategorized Expenses', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 131),
    ('QB-21056', '21056', 'expense', 'Expenses', 'Taxes Paid', 132),
    ('QB-6114 FICA Employer', '6114 FICA Employer', 'expense', 'Expenses', 'Payroll Expenses', 133),
    ('QB-Insurance', 'Insurance', 'expense', 'Expenses', 'Insurance', 134),
    ('6401', 'Insurance:WC,Liability & Auto', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 135),
    ('6403', 'Insurance:Health Ins. Emp.', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 136),
    ('6404', 'Insurance:Vehicle Insurance', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 137),
    ('6405', 'Insurance:Umbrella Insurance', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 138),
    ('6702', 'Insurance:Tailored Protection Insurance', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 139),
    ('QB-Payroll Expenses', 'Payroll Expenses', 'expense', 'Expenses', 'Payroll Expenses', 140),
    ('6103', 'Payroll Expenses:Officer Wages', 'expense', 'Expenses', 'Cost of Labor', 141),
    ('QB-Payroll Expenses:Taxes', 'Payroll Expenses:Taxes', 'expense', 'Expenses', 'Payroll Expenses', 142),
    ('QB-Payroll Expenses:Wages', 'Payroll Expenses:Wages', 'expense', 'Expenses', 'Payroll Expenses', 143),
    ('QB-Purchases', 'Purchases', 'expense', 'Expenses', 'Supplies & Materials', 144),
    ('QB-Unapplied Cash Bill Payment Expense', 'Unapplied Cash Bill Payment Expense', 'expense', 'Expenses', 'Unapplied Cash Bill Payment Expense', 145),
    ('QB-Uncategorized Expense', 'Uncategorized Expense', 'expense', 'Expenses', 'Other Miscellaneous Service Cost', 146),
    ('6505', 'Gain/ Loss Sale of Assets', 'revenue', 'Other Income', 'Other Miscellaneous Income', 147),
    ('QB-Interest Income', 'Interest Income', 'revenue', 'Other Income', 'Interest Earned', 148),
    ('6201', 'Bad Debt Expense', 'expense', 'Other Expense', 'Other Miscellaneous Expense', 149),
    ('6301', 'Deprec. Vehicles', 'expense', 'Other Expense', 'Depreciation', 150),
    ('6302', 'Deprec. Furn./Fixtures', 'expense', 'Other Expense', 'Depreciation', 151),
    ('6303', 'Deprec. Office Equipment', 'expense', 'Other Expense', 'Depreciation', 152),
    ('6304', 'Vehicle purchase', 'expense', 'Other Expense', 'Vehicle', 153),
    ('6906', 'Penalty on taxes', 'expense', 'Other Expense', 'Penalties & Settlements', 154),
    ('QB-Half Cent Account*', 'Half Cent Account*', 'expense', 'Other Expense', 'Other Miscellaneous Expense', 155),
    ('QB-Other Income/Expense', 'Other Income/Expense', 'expense', 'Other Expense', 'Other Miscellaneous Expense', 156),
    ('QB-Reconciliation Discrepancies', 'Reconciliation Discrepancies', 'expense', 'Other Expense', 'Other Miscellaneous Expense', 157)
)
insert into public.accounts (code, name, type, qbo_account_type, detail_type, sort_order, active, created_at, updated_at)
select code, name, type, qbo_account_type, detail_type, sort_order, true, now(), now()
from recon_accounts
on conflict (code) do update set
  name = excluded.name,
  type = excluded.type,
  qbo_account_type = excluded.qbo_account_type,
  detail_type = excluded.detail_type,
  sort_order = excluded.sort_order,
  active = true,
  updated_at = now();

commit;
